__Note__: The code used here was heavily inspired by the AI for Medicine Specialization Course 1 Week three programming assignments: [link](https://www.coursera.org/learn/ai-for-medical-diagnosis)

In [1]:
import numpy as np
import nibabel as nib
import matplotlib.pyplot as plt
import json
import os
from pprint import pprint
from collections import OrderedDict
from ipywidgets import interact, interactive, IntSlider, ToggleButtons
from sys import getsizeof
from tqdm import tqdm

### Reading dataset description

In [2]:
file = open('../datasets_descriptions_json/task02_heart_dataset.json')
data_description = json.load(file)

In [3]:
print(json.dumps(data_description, indent=4))

{
    "name": "LeftAtrium",
    "description": "Left atrium segmentation",
    "tensorImageSize": "3D",
    "reference": "King\u2019s College London",
    "licence": "CC-BY-SA 4.0",
    "relase": "1.0 04/05/2018",
    "modality": {
        "0": "MRI"
    },
    "labels": {
        "0": "background",
        "1": "left atrium"
    },
    "numTraining": 20,
    "numTest": 10,
    "training": [
        {
            "image": "./imagesTr/la_007.nii.gz",
            "label": "./labelsTr/la_007.nii.gz"
        },
        {
            "image": "./imagesTr/la_019.nii.gz",
            "label": "./labelsTr/la_019.nii.gz"
        },
        {
            "image": "./imagesTr/la_023.nii.gz",
            "label": "./labelsTr/la_023.nii.gz"
        },
        {
            "image": "./imagesTr/la_005.nii.gz",
            "label": "./labelsTr/la_005.nii.gz"
        },
        {
            "image": "./imagesTr/la_009.nii.gz",
            "label": "./labelsTr/la_009.nii.gz"
        },
        {
     

### Reading and visualizing LA_003 nifti MRI and mask files

#### MRI file

In [4]:
mri_1 = nib.load("../../datasets/Task02_Heart/train/images/la_003.nii.gz")

In [5]:
type(mri_1)

nibabel.nifti1.Nifti1Image

In [6]:
# Read Nifi Image object as numpy file
mri_1 = mri_1.get_fdata()

In [7]:
type(mri_1)

numpy.ndarray

In [8]:
mri_1.dtype

dtype('float64')

In [9]:
mri_1.shape

(320, 320, 130)

In [10]:
# Range of voxel values (maximum value - minimum value)
print(mri_1.ptp())

1999.0


In [11]:
getsizeof(mri_1) # 106.496128 MBs

106496128

In [12]:
getsizeof(mri_1.astype(np.float32)) # 53.248128 MBs

53248128

In [13]:
getsizeof(mri_1.astype(np.float16)) # 26.624128 MBs

26624128

#### Mask file

In [14]:
mri_1_mask = nib.load("../../datasets/Task02_Heart/train/masks/la_003.nii.gz")

In [15]:
mri_1_mask = mri_1_mask.get_fdata()

In [16]:
mri_1_mask.dtype

dtype('float64')

In [17]:
np.unique(mri_1_mask)

array([0., 1.])

In [18]:
mri_1_mask.shape

(320, 320, 130)

In [19]:
getsizeof(mri_1_mask) # 106.496128 MBs

106496128

In [20]:
getsizeof(mri_1_mask.astype(np.float32)) # 53.248128 MBs

53248128

In [21]:
getsizeof(mri_1_mask.astype(np.uint8)) # 13.312128 MBs

13312128

In [22]:
mri_1_mask = mri_1_mask.astype(np.float32)

### Visualizing nifti MRI file and Mask file

In [23]:
# Create layer slider
select_layer = IntSlider(min=0, max=mri_1.shape[2] - 1, description='Select Layer', continuous_update=False)

    
# Define a function for plotting images
def plot(layer):
    print(f"Plotting Layer: {layer}")
    fig = plt.figure(figsize=(20, 10))
    
    fig.add_subplot(1, 2, 1)
    plt.imshow(mri_1[:, :, layer], cmap='gray');
    plt.title("MRI", fontsize=20)
    plt.axis('off')
    
    fig.add_subplot(1, 2, 2)
    plt.title("Mask", fontsize=20)
    plt.imshow(mri_1_mask[:, :, layer], cmap='gray');
    plt.axis('off');

    
# Use the interactive() tool to create the visualization
interactive(plot, layer=select_layer)

interactive(children=(IntSlider(value=0, continuous_update=False, description='Select Layer', max=129), Output…

### Reading and visualizing LA_004 nifti MRI and mask files

#### MRI file

In [24]:
mri_2 = nib.load("../../datasets/Task02_Heart/train/images/la_004.nii.gz")

In [25]:
type(mri_2)

nibabel.nifti1.Nifti1Image

In [26]:
# Read Nifi Image object as numpy file
mri_2 = mri_2.get_fdata()

In [27]:
type(mri_2)

numpy.ndarray

In [28]:
mri_2.dtype

dtype('float64')

In [29]:
mri_2.shape

(320, 320, 110)

In [30]:
# Range of voxel values (maximum value - minimum value)
print(mri_2.ptp())

1811.0


#### Mask file

In [31]:
mri_2_mask = nib.load("../../datasets/Task02_Heart/train/masks/la_004.nii.gz")

In [32]:
mri_2_mask = mri_2_mask.get_fdata()

In [33]:
mri_2_mask.dtype

dtype('float64')

In [34]:
np.unique(mri_2_mask)

array([0., 1.])

In [35]:
mri_2_mask.shape

(320, 320, 110)

In [36]:
mri_2_mask = mri_2_mask.astype(np.float32)

### Visualizing nifti MRI file and Mask file

In [37]:
# Create layer slider
select_layer = IntSlider(min=0, max=mri_2.shape[2] - 1, description='Select Layer', continuous_update=False)

    
# Define a function for plotting images
def plot(layer):
    print(f"Plotting Layer: {layer}")
    fig = plt.figure(figsize=(20, 10))
    
    fig.add_subplot(1, 2, 1)
    plt.imshow(mri_2[:, :, layer], cmap='gray');
    plt.title("MRI", fontsize=20)
    plt.axis('off')
    
    fig.add_subplot(1, 2, 2)
    plt.title("Mask", fontsize=20)
    plt.imshow(mri_2_mask[:, :, layer], cmap='gray');
    plt.axis('off');

    
# Use the interactive() tool to create the visualization
interactive(plot, layer=select_layer)

interactive(children=(IntSlider(value=0, continuous_update=False, description='Select Layer', max=109), Output…

### Reading and visualizing LA_005 nifti MRI and mask files

#### MRI file

In [38]:
mri_3 = nib.load("../../datasets/Task02_Heart/train/images/la_005.nii.gz")

In [39]:
type(mri_3)

nibabel.nifti1.Nifti1Image

In [40]:
# Read Nifi Image object as numpy file
mri_3 = mri_3.get_fdata()

In [41]:
type(mri_3)

numpy.ndarray

In [42]:
mri_3.dtype

dtype('float64')

In [43]:
mri_3.shape

(320, 320, 120)

In [44]:
# Range of voxel values (maximum value - minimum value)
print(mri_3.ptp())

1888.0


#### Mask file

In [45]:
mri_3_mask = nib.load("../../datasets/Task02_Heart/train/masks/la_005.nii.gz")

In [46]:
mri_3_mask = mri_3_mask.get_fdata()

In [47]:
mri_3_mask.dtype

dtype('float64')

In [48]:
np.unique(mri_3_mask)

array([0., 1.])

In [49]:
mri_3_mask.shape

(320, 320, 120)

In [50]:
mri_3_mask = mri_3_mask.astype(np.float32)

### Visualizing nifti MRI file and Mask file

In [51]:
# Create layer slider
select_layer = IntSlider(min=0, max=mri_3.shape[2] - 1, description='Select Layer', continuous_update=False)

    
# Define a function for plotting images
def plot(layer):
    print(f"Plotting Layer: {layer}")
    fig = plt.figure(figsize=(20, 10))
    
    fig.add_subplot(1, 2, 1)
    plt.imshow(mri_3[:, :, layer], cmap='gray');
    plt.title("MRI", fontsize=20)
    plt.axis('off')
    
    fig.add_subplot(1, 2, 2)
    plt.title("Mask", fontsize=20)
    plt.imshow(mri_3_mask[:, :, layer], cmap='gray');
    plt.axis('off');

    
# Use the interactive() tool to create the visualization
interactive(plot, layer=select_layer)

interactive(children=(IntSlider(value=0, continuous_update=False, description='Select Layer', max=119), Output…

### Calculating MRI shape counter dictionary

In [52]:
data_dir = "../../datasets/Task02_Heart/"

train_mri_paths = [os.path.join(data_dir + "train/images", x) for x in os.listdir(data_dir + "train/images")]
val_mri_paths = [os.path.join(data_dir + "val/images", x) for x in os.listdir(data_dir + "val/images")]
test_mri_paths = [os.path.join(data_dir + "test_images_for_model_prediction_submission", x) for x in os.listdir(data_dir + "test_images_for_model_prediction_submission")]

all_paths = train_mri_paths + val_mri_paths + test_mri_paths  # concatenate list of paths

shape_count_dict = {}

for path in tqdm(all_paths):
    mri = nib.load(path).get_fdata()
    shape = mri.shape
    
    if shape not in shape_count_dict.keys():
        shape_count_dict[shape] = 1
    else:
        shape_count_dict[shape] += 1   

100%|██████████| 30/30 [00:06<00:00,  4.50it/s]


In [53]:
shape_count_dict = OrderedDict(sorted(shape_count_dict.items(), key=lambda item: item[1], reverse=True))
pprint(shape_count_dict)

OrderedDict([((320, 320, 120), 9),
             ((320, 320, 110), 7),
             ((320, 320, 100), 5),
             ((320, 320, 130), 2),
             ((400, 400, 180), 2),
             ((320, 320, 90), 1),
             ((320, 320, 122), 1),
             ((320, 320, 109), 1),
             ((320, 320, 140), 1),
             ((320, 320, 137), 1)])


In [54]:
list_layers = []
for key, val in shape_count_dict.items():
    list_layers.append(key[2])

layers = np.array(list_layers)
print(layers.mean())
print(np.median(layers))
print(layers.min())
print(layers.max())

123.8
121.0
90
180
