__Note__: The code used here was heavily inspired by the AI for Medicine Specialization Course 1 Week three programming assignments: [link](https://www.coursera.org/learn/ai-for-medical-diagnosis)

In [1]:
import numpy as np
import nibabel as nib
import matplotlib.pyplot as plt
import json
import os
from pprint import pprint
from collections import OrderedDict
from ipywidgets import interact, interactive, IntSlider, ToggleButtons
from sys import getsizeof
from tqdm import tqdm

### Reading dataset description

In [2]:
file = open('../datasets_descriptions_json/task07_pancreas_dataset.json')
data_description = json.load(file)

In [3]:
print(json.dumps(data_description, indent=4))

{
    "name": "Pancreas",
    "description": "Pancreas and cancer segmentation",
    "reference": "Memorial Sloan Kettering Cancer Center ",
    "licence": "CC-BY-SA 4.0",
    "relase": "1.0 04/05/2018",
    "tensorImageSize": "3D",
    "modality": {
        "0": "CT"
    },
    "labels": {
        "0": "background",
        "1": "pancreas",
        "2": "cancer"
    },
    "numTraining": 281,
    "numTest": 139,
    "training": [
        {
            "image": "./imagesTr/pancreas_290.nii.gz",
            "label": "./labelsTr/pancreas_290.nii.gz"
        },
        {
            "image": "./imagesTr/pancreas_127.nii.gz",
            "label": "./labelsTr/pancreas_127.nii.gz"
        },
        {
            "image": "./imagesTr/pancreas_056.nii.gz",
            "label": "./labelsTr/pancreas_056.nii.gz"
        },
        {
            "image": "./imagesTr/pancreas_148.nii.gz",
            "label": "./labelsTr/pancreas_148.nii.gz"
        },
        {
            "image": "./imagesTr/pa

### Reading and visualizing pancreas_001 nifti CT and mask files

#### CT file

In [4]:
ct_1 = nib.load("../../datasets/Task07_Pancreas/train/images/pancreas_001.nii.gz")

In [5]:
type(ct_1)

nibabel.nifti1.Nifti1Image

In [6]:
# Read Nifi Image object as numpy file
ct_1 = ct_1.get_fdata()

In [7]:
type(ct_1)

numpy.ndarray

In [8]:
ct_1.dtype

dtype('float64')

In [9]:
ct_1.shape

(512, 512, 110)

In [10]:
# Range of voxel values (maximum value - minimum value)
print(ct_1[:, :, :].ptp())

4095.0


In [11]:
getsizeof(ct_1) # 230.686848 MBs

230686848

In [12]:
getsizeof(ct_1.astype(np.float32)) # 115.343488 MBs

115343488

In [13]:
getsizeof(ct_1.astype(np.float16)) # 57.671808 MBs

57671808

#### Mask file

In [14]:
ct_1_mask = nib.load("../../datasets/Task07_Pancreas/train/masks/pancreas_001.nii.gz")

In [15]:
ct_1_mask = ct_1_mask.get_fdata()

In [16]:
ct_1_mask.dtype

dtype('float64')

In [17]:
np.unique(ct_1_mask)

array([0., 1., 2.])

In [18]:
getsizeof(ct_1_mask) # 230.686848 MBs

230686848

In [19]:
getsizeof(ct_1_mask.astype(np.float32)) # 115.343488 MBs

115343488

In [20]:
getsizeof(ct_1_mask.astype(np.uint8)) # 28.835968 MBs

28835968

In [21]:
ct_1_mask = ct_1_mask.astype(np.float32)

In [22]:
ct_1_mask.shape

(512, 512, 110)

### Visualizing nifti CT file and Mask file

In [23]:
classes_dict = {
    'Background': 0,
    'Pancreas': 1,
    'Cancer': 2
}

# Create button values
select_class = ToggleButtons(
    options=['Background', 'Pancreas', 'Cancer', 'All'],
    description='Select Class:',
    disabled=False,
    button_style='info', 
    
)
# Create layer slider
select_layer = IntSlider(min=0, max=ct_1.shape[2] - 1, description='Select Layer', continuous_update=False)

    
# Define a function for plotting images
def plot(seg_class, layer):
    print(f"Plotting Layer: {layer} | Label: {seg_class}")
    fig = plt.figure(figsize=(20, 10))
    
    fig.add_subplot(1, 2, 1)
    plt.imshow(ct_1[:, :, layer], cmap='gray');
    plt.title("ct", fontsize=20)
    plt.axis('off')
    
    fig.add_subplot(1, 2, 2)
    if seg_class == "All":
        mask = ct_1_mask[:, :, layer]
        plt.title("Mask", fontsize=20)
        plt.imshow(mask)
        plt.axis('off');
    else:
        img_label = classes_dict[seg_class]
        mask = np.where(ct_1_mask[:, :, layer] == img_label, 255, 0)
        plt.title("Mask", fontsize=20)
        plt.imshow(mask, cmap='gray')
        plt.axis('off');

# Use the interactive() tool to create the visualization
interactive(plot, seg_class=select_class, layer=select_layer)

interactive(children=(ToggleButtons(button_style='info', description='Select Class:', options=('Background', '…

### Reading and visualizing pancreas_004 nifti CT and mask files

#### CT file

In [24]:
ct_2 = nib.load("../../datasets/Task07_Pancreas/train/images/pancreas_004.nii.gz")

In [25]:
type(ct_2)

nibabel.nifti1.Nifti1Image

In [26]:
# Read Nifi Image object as numpy file
ct_2 = ct_2.get_fdata()

In [27]:
type(ct_2)

numpy.ndarray

In [28]:
ct_2.dtype

dtype('float64')

In [29]:
ct_2.shape

(512, 512, 107)

In [30]:
# Range of voxel values (maximum value - minimum value)
print(ct_2[:, :, :].ptp())

3950.0


#### Mask file

In [31]:
ct_2_mask = nib.load("../../datasets/Task07_Pancreas/train/masks/pancreas_004.nii.gz")

In [32]:
ct_2_mask = ct_2_mask.get_fdata()

In [33]:
ct_2_mask.dtype

dtype('float64')

In [34]:
np.unique(ct_2_mask)

array([0., 1., 2.])

In [35]:
ct_2_mask = ct_2_mask.astype(np.float32)

In [36]:
ct_2_mask.shape

(512, 512, 107)

### Visualizing nifti CT file and Mask file

In [37]:
classes_dict = {
    'Background': 0,
    'Pancreas': 1,
    'Cancer': 2
}

# Create button values
select_class = ToggleButtons(
    options=['Background', 'Pancreas', 'Cancer', 'All'],
    description='Select Class:',
    disabled=False,
    button_style='info', 
    
)
# Create layer slider
select_layer = IntSlider(min=0, max=ct_2.shape[2] - 1, description='Select Layer', continuous_update=False)

    
# Define a function for plotting images
def plot(seg_class, layer):
    print(f"Plotting Layer: {layer} | Label: {seg_class}")
    fig = plt.figure(figsize=(20, 10))
    
    fig.add_subplot(1, 2, 1)
    plt.imshow(ct_2[:, :, layer], cmap='gray');
    plt.title("ct", fontsize=20)
    plt.axis('off')
    
    fig.add_subplot(1, 2, 2)
    if seg_class == "All":
        mask = ct_2_mask[:, :, layer]
        plt.title("Mask", fontsize=20)
        plt.imshow(mask)
        plt.axis('off');
    else:
        img_label = classes_dict[seg_class]
        mask = np.where(ct_2_mask[:, :, layer] == img_label, 255, 0)
        plt.title("Mask", fontsize=20)
        plt.imshow(mask, cmap='gray')
        plt.axis('off');

# Use the interactive() tool to create the visualization
interactive(plot, seg_class=select_class, layer=select_layer)

interactive(children=(ToggleButtons(button_style='info', description='Select Class:', options=('Background', '…

### Reading and visualizing pancreas_005 nifti CT and mask files

#### CT file

In [38]:
ct_3 = nib.load("../../datasets/Task07_Pancreas/train/images/pancreas_005.nii.gz")

In [39]:
type(ct_3)

nibabel.nifti1.Nifti1Image

In [40]:
# Read Nifi Image object as numpy file
ct_3 = ct_3.get_fdata()

In [41]:
type(ct_3)

numpy.ndarray

In [42]:
ct_3.dtype

dtype('float64')

In [43]:
ct_3.shape

(512, 512, 104)

In [44]:
# Range of voxel values (maximum value - minimum value)
print(ct_3[:, :, :].ptp())

3122.0


#### Mask file

In [45]:
ct_3_mask = nib.load("../../datasets/Task07_Pancreas/train/masks/pancreas_005.nii.gz")

In [46]:
ct_3_mask = ct_3_mask.get_fdata()

In [47]:
ct_3_mask.dtype

dtype('float64')

In [48]:
np.unique(ct_3_mask)

array([0., 1., 2.])

In [49]:
ct_3_mask = ct_3_mask.astype(np.float32)

In [50]:
ct_3_mask.shape

(512, 512, 104)

### Visualizing nifti CT file and Mask file

In [51]:
classes_dict = {
    'Background': 0,
    'Pancreas': 1,
    'Cancer': 2
}

# Create button values
select_class = ToggleButtons(
    options=['Background', 'Pancreas', 'Cancer', 'All'],
    description='Select Class:',
    disabled=False,
    button_style='info', 
    
)
# Create layer slider
select_layer = IntSlider(min=0, max=ct_3.shape[2] - 1, description='Select Layer', continuous_update=False)

    
# Define a function for plotting images
def plot(seg_class, layer):
    print(f"Plotting Layer: {layer} | Label: {seg_class}")
    fig = plt.figure(figsize=(20, 10))
    
    fig.add_subplot(1, 2, 1)
    plt.imshow(ct_3[:, :, layer], cmap='gray');
    plt.title("ct", fontsize=20)
    plt.axis('off')
    
    fig.add_subplot(1, 2, 2)
    if seg_class == "All":
        mask = ct_3_mask[:, :, layer]
        plt.title("Mask", fontsize=20)
        plt.imshow(mask)
        plt.axis('off');
    else:
        img_label = classes_dict[seg_class]
        mask = np.where(ct_3_mask[:, :, layer] == img_label, 255, 0)
        plt.title("Mask", fontsize=20)
        plt.imshow(mask, cmap='gray')
        plt.axis('off');

# Use the interactive() tool to create the visualization
interactive(plot, seg_class=select_class, layer=select_layer)

interactive(children=(ToggleButtons(button_style='info', description='Select Class:', options=('Background', '…

### Calculating CT shape counter dictionary

In [52]:
data_dir = "../../datasets/Task07_Pancreas/"

train_mri_paths = [os.path.join(data_dir + "train/images", x) for x in os.listdir(data_dir + "train/images")]
val_mri_paths = [os.path.join(data_dir + "val/images", x) for x in os.listdir(data_dir + "val/images")]
test_mri_paths = [os.path.join(data_dir + "test_images_for_model_prediction_submission", x) for x in os.listdir(data_dir + "test_images_for_model_prediction_submission")]

all_paths = train_mri_paths + val_mri_paths + test_mri_paths  # concatenate list of paths

shape_count_dict = {}

for path in tqdm(all_paths):
    mri = nib.load(path).get_fdata()
    shape = mri.shape
    
    if shape not in shape_count_dict.keys():
        shape_count_dict[shape] = 1
    else:
        shape_count_dict[shape] += 1   

100%|██████████| 420/420 [03:00<00:00,  2.32it/s]


In [53]:
shape_count_dict = OrderedDict(sorted(shape_count_dict.items(), key=lambda item: item[1], reverse=True))
pprint(shape_count_dict)

OrderedDict([((512, 512, 89), 24),
             ((512, 512, 93), 21),
             ((512, 512, 97), 21),
             ((512, 512, 95), 19),
             ((512, 512, 87), 16),
             ((512, 512, 99), 15),
             ((512, 512, 85), 13),
             ((512, 512, 101), 13),
             ((512, 512, 81), 13),
             ((512, 512, 103), 12),
             ((512, 512, 83), 10),
             ((512, 512, 98), 10),
             ((512, 512, 91), 10),
             ((512, 512, 105), 9),
             ((512, 512, 107), 9),
             ((512, 512, 84), 8),
             ((512, 512, 79), 7),
             ((512, 512, 113), 7),
             ((512, 512, 96), 6),
             ((512, 512, 77), 6),
             ((512, 512, 92), 6),
             ((512, 512, 73), 6),
             ((512, 512, 109), 6),
             ((512, 512, 51), 5),
             ((512, 512, 75), 5),
             ((512, 512, 121), 5),
             ((512, 512, 104), 5),
             ((512, 512, 100), 5),
             ((512, 512, 5

In [54]:
list_layers = []
for key, val in shape_count_dict.items():
    list_layers.append(key[2])

layers = np.array(list_layers)
print(layers.mean())
print(np.median(layers))
print(layers.min())
print(layers.max())

109.1919191919192
93.0
37
751
