__Note__: The code used here was heavily inspired by the AI for Medicine Specialization Course 1 Week three programming assignments: [link](https://www.coursera.org/learn/ai-for-medical-diagnosis)

In [1]:
import numpy as np
import nibabel as nib
import matplotlib.pyplot as plt
import json
import os
from pprint import pprint
from collections import OrderedDict
from ipywidgets import interact, interactive, IntSlider, ToggleButtons
from sys import getsizeof
from tqdm import tqdm

### Reading dataset description

In [2]:
file = open('../datasets_descriptions_json/task04_hippocampus_dataset.json')
data_description = json.load(file)

In [3]:
print(json.dumps(data_description, indent=4))

{
    "name": "Hippocampus",
    "description": "Left and right hippocampus segmentation",
    "reference": " Vanderbilt University Medical Center",
    "licence": "CC-BY-SA 4.0",
    "relase": "1.0 04/05/2018",
    "tensorImageSize": "3D",
    "modality": {
        "0": "MRI"
    },
    "labels": {
        "0": "background",
        "1": "Anterior",
        "2": "Posterior"
    },
    "numTraining": 260,
    "numTest": 130,
    "training": [
        {
            "image": "./imagesTr/hippocampus_367.nii.gz",
            "label": "./labelsTr/hippocampus_367.nii.gz"
        },
        {
            "image": "./imagesTr/hippocampus_304.nii.gz",
            "label": "./labelsTr/hippocampus_304.nii.gz"
        },
        {
            "image": "./imagesTr/hippocampus_204.nii.gz",
            "label": "./labelsTr/hippocampus_204.nii.gz"
        },
        {
            "image": "./imagesTr/hippocampus_279.nii.gz",
            "label": "./labelsTr/hippocampus_279.nii.gz"
        },
        {

### Reading and visualizing hippocampus_001 nifti MRI and mask files

#### MRI file

In [4]:
mri_1 = nib.load("../../datasets/Task04_Hippocampus/train/images/hippocampus_001.nii.gz")

In [5]:
type(mri_1)

nibabel.nifti1.Nifti1Image

In [6]:
# Read Nifi Image object as numpy file
mri_1 = mri_1.get_fdata()

In [7]:
type(mri_1)

numpy.ndarray

In [8]:
mri_1.dtype

dtype('float64')

In [9]:
mri_1.shape

(35, 51, 35)

In [10]:
# Range of voxel values (maximum value - minimum value)
print(mri_1[:, :, :].ptp())

137.0


In [11]:
getsizeof(mri_1) # 0.499928 MBs

499928

In [12]:
getsizeof(mri_1.astype(np.float32)) # 0.250028 MBs

250028

In [13]:
getsizeof(mri_1.astype(np.float16)) # 0.125078 MBs

125078

#### Mask file

In [14]:
mri_1_mask = nib.load("../../datasets/Task04_Hippocampus/train/masks/hippocampus_001.nii.gz")

In [15]:
mri_1_mask = mri_1_mask.get_fdata()

In [16]:
mri_1_mask.dtype

dtype('float64')

In [17]:
np.unique(mri_1_mask)

array([0., 1., 2.])

In [18]:
getsizeof(mri_1_mask) # 0.499928 MBs

499928

In [19]:
getsizeof(mri_1_mask.astype(np.float32)) # 0.250028 MBs

250028

In [20]:
getsizeof(mri_1_mask.astype(np.uint8)) # 0.062603 MBs

62603

In [21]:
mri_1_mask = mri_1_mask.astype(np.float32)

In [22]:
mri_1_mask.shape

(35, 51, 35)

### Visualizing nifti MRI file and Mask file

In [23]:
classes_dict = {
    'Background': 0,
    'Anterior': 1,
    'Posterior': 2
}

# Create button values
select_class = ToggleButtons(
    options=['Background','Anterior', 'Posterior', 'All'],
    description='Select Class:',
    disabled=False,
    button_style='info', 
    
)
# Create layer slider
select_layer = IntSlider(min=0, max=mri_1.shape[2] - 1, description='Select Layer', continuous_update=False)

    
# Define a function for plotting images
def plot(seg_class, layer):
    print(f"Plotting Layer: {layer} | Label: {seg_class}")
    fig = plt.figure(figsize=(20, 10))
    
    fig.add_subplot(1, 2, 1)
    plt.imshow(mri_1[:, :, layer], cmap='gray');
    plt.title("MRI", fontsize=20)
    plt.axis('off')
    
    fig.add_subplot(1, 2, 2)
    img_label = classes_dict[seg_class]
    mask = np.where(mri_1_mask[:, :, layer] == img_label, 255, 0)
    plt.title("Mask", fontsize=20)
    plt.imshow(mask, cmap='gray')
    plt.axis('off');
    
# Use the interactive() tool to create the visualization
interactive(plot, seg_class=select_class, layer=select_layer)

interactive(children=(ToggleButtons(button_style='info', description='Select Class:', options=('Background', '…

### Reading and visualizing hippocampus_003 nifti MRI and mask files

#### MRI file

In [24]:
mri_2 = nib.load("../../datasets/Task04_Hippocampus/train/images/hippocampus_003.nii.gz")

In [25]:
type(mri_2)

nibabel.nifti1.Nifti1Image

In [26]:
# Read Nifi Image object as numpy file
mri_2 = mri_2.get_fdata()

In [27]:
type(mri_2)

numpy.ndarray

In [28]:
mri_2.dtype

dtype('float64')

In [29]:
mri_2.shape

(34, 52, 35)

In [30]:
# Range of voxel values (maximum value - minimum value)
print(mri_2[:, :, :].ptp())

2776.880126953125


#### Mask file

In [31]:
mri_2_mask = nib.load("../../datasets/Task04_Hippocampus/train/masks/hippocampus_003.nii.gz")

In [32]:
mri_2_mask = mri_2_mask.get_fdata()

In [33]:
mri_2_mask.dtype

dtype('float64')

In [34]:
np.unique(mri_2_mask)

array([0., 1., 2.])

In [35]:
mri_2_mask = mri_2_mask.astype(np.float32)

In [36]:
mri_2_mask.shape

(34, 52, 35)

### Visualizing nifti MRI file and Mask file

In [37]:
classes_dict = {
    'Background': 0,
    'Anterior': 1,
    'Posterior': 2
}

# Create button values
select_class = ToggleButtons(
    options=['Background','Anterior', 'Posterior', 'All'],
    description='Select Class:',
    disabled=False,
    button_style='info', 
    
)
# Create layer slider
select_layer = IntSlider(min=0, max=mri_2.shape[2] - 1, description='Select Layer', continuous_update=False)

    
# Define a function for plotting images
def plot(seg_class, layer):
    print(f"Plotting Layer: {layer} | Label: {seg_class}")
    fig = plt.figure(figsize=(20, 10))
    
    fig.add_subplot(1, 2, 1)
    plt.imshow(mri_2[:, :, layer], cmap='gray');
    plt.title("MRI", fontsize=20)
    plt.axis('off')
    
    fig.add_subplot(1, 2, 2)
    img_label = classes_dict[seg_class]
    mask = np.where(mri_2_mask[:, :, layer] == img_label, 255, 0)
    plt.title("Mask", fontsize=20)
    plt.imshow(mask, cmap='gray')
    plt.axis('off');
    
# Use the interactive() tool to create the visualization
interactive(plot, seg_class=select_class, layer=select_layer)

interactive(children=(ToggleButtons(button_style='info', description='Select Class:', options=('Background', '…

### Reading and visualizing hippocampus_004 nifti MRI and mask files

#### MRI file

In [38]:
mri_3 = nib.load("../../datasets/Task04_Hippocampus/train/images/hippocampus_004.nii.gz")

In [39]:
type(mri_3)

nibabel.nifti1.Nifti1Image

In [40]:
# Read Nifi Image object as numpy file
mri_3 = mri_3.get_fdata()

In [41]:
type(mri_3)

numpy.ndarray

In [42]:
mri_3.dtype

dtype('float64')

In [43]:
mri_3.shape

(36, 52, 38)

In [44]:
# Range of voxel values (maximum value - minimum value)
print(mri_3[:, :, :].ptp())

2252.49072265625


#### Mask file

In [45]:
mri_3_mask = nib.load("../../datasets/Task04_Hippocampus/train/masks/hippocampus_004.nii.gz")

In [46]:
mri_3_mask = mri_3_mask.get_fdata()

In [47]:
mri_3_mask.dtype

dtype('float64')

In [48]:
np.unique(mri_3_mask)

array([0., 1., 2.])

In [49]:
mri_3_mask = mri_3_mask.astype(np.float32)

In [50]:
mri_3_mask.shape

(36, 52, 38)

### Visualizing nifti MRI file and Mask file

In [51]:
classes_dict = {
    'Background': 0,
    'Anterior': 1,
    'Posterior': 2
}

# Create button values
select_class = ToggleButtons(
    options=['Background','Anterior', 'Posterior', 'All'],
    description='Select Class:',
    disabled=False,
    button_style='info', 
    
)
# Create layer slider
select_layer = IntSlider(min=0, max=mri_3.shape[2] - 1, description='Select Layer', continuous_update=False)

    
# Define a function for plotting images
def plot(seg_class, layer):
    print(f"Plotting Layer: {layer} | Label: {seg_class}")
    fig = plt.figure(figsize=(20, 10))
    
    fig.add_subplot(1, 2, 1)
    plt.imshow(mri_3[:, :, layer], cmap='gray');
    plt.title("MRI", fontsize=20)
    plt.axis('off')
    
    fig.add_subplot(1, 2, 2)
    if seg_class == "All":
        mask = mri_3_mask[:, :, layer]
        plt.title("Mask", fontsize=20)
        plt.imshow(mask)
        plt.axis('off');
    else:
        img_label = classes_dict[seg_class]
        mask = np.where(mri_3_mask[:, :, layer] == img_label, 255, 0)
        plt.title("Mask", fontsize=20)
        plt.imshow(mask, cmap='gray')
        plt.axis('off');
    
# Use the interactive() tool to create the visualization
interactive(plot, seg_class=select_class, layer=select_layer)

interactive(children=(ToggleButtons(button_style='info', description='Select Class:', options=('Background', '…

### Calculating MRI shape counter dictionary

In [52]:
data_dir = "../../datasets/Task04_Hippocampus/"

train_mri_paths = [os.path.join(data_dir + "train/images", x) for x in os.listdir(data_dir + "train/images")]
val_mri_paths = [os.path.join(data_dir + "val/images", x) for x in os.listdir(data_dir + "val/images")]
test_mri_paths = [os.path.join(data_dir + "test_images_for_model_prediction_submission", x) for x in os.listdir(data_dir + "test_images_for_model_prediction_submission")]

all_paths = train_mri_paths + val_mri_paths + test_mri_paths  # concatenate list of paths

shape_count_dict = {}

for path in tqdm(all_paths):
    mri = nib.load(path).get_fdata()
    shape = mri.shape
    
    if shape not in shape_count_dict.keys():
        shape_count_dict[shape] = 1
    else:
        shape_count_dict[shape] += 1   

100%|██████████| 390/390 [00:00<00:00, 657.76it/s]


In [53]:
shape_count_dict = OrderedDict(sorted(shape_count_dict.items(), key=lambda item: item[1], reverse=True))
pprint(shape_count_dict)

OrderedDict([((37, 51, 33), 3),
             ((34, 53, 34), 3),
             ((34, 53, 37), 3),
             ((37, 49, 34), 3),
             ((35, 51, 36), 3),
             ((35, 51, 34), 3),
             ((35, 51, 35), 3),
             ((36, 52, 32), 3),
             ((34, 53, 36), 2),
             ((32, 47, 41), 2),
             ((34, 52, 35), 2),
             ((34, 48, 40), 2),
             ((36, 51, 34), 2),
             ((35, 49, 40), 2),
             ((32, 52, 34), 2),
             ((36, 51, 35), 2),
             ((35, 53, 33), 2),
             ((36, 53, 37), 2),
             ((38, 52, 33), 2),
             ((35, 52, 34), 2),
             ((36, 48, 38), 2),
             ((37, 49, 37), 2),
             ((37, 51, 35), 2),
             ((34, 51, 38), 2),
             ((35, 49, 33), 2),
             ((32, 54, 34), 2),
             ((38, 51, 37), 2),
             ((35, 50, 36), 2),
             ((35, 48, 35), 2),
             ((35, 46, 42), 2),
             ((37, 48, 34), 2),
        

In [54]:
list_layers = []
for key, val in shape_count_dict.items():
    list_layers.append(key[2])

layers = np.array(list_layers)
print(layers.mean())
print(np.median(layers))
print(layers.min())
print(layers.max())

35.375
35.0
24
47


In [55]:
list_heights = []
list_widths = []

for key, val in shape_count_dict.items():
    list_heights.append(key[0])
    list_widths.append(key[1])

heights = np.array(list_heights)
widths = np.array(list_widths)

print(heights.mean())
print(np.median(heights))
print(heights.min())
print(heights.max())
print("----------------------")
print(widths.mean())
print(np.median(widths))
print(widths.min())
print(widths.max())

35.37202380952381
35.0
30
43
----------------------
49.92559523809524
50.0
40
59
