### For checking the model prediction files for the challenge submission

In [9]:
import numpy as np
import nibabel as nib
import matplotlib.pyplot as plt
from ipywidgets import interact, interactive, IntSlider, ToggleButtons

### Visualizing prediction on BRATS_485 file

In [10]:
mri = nib.load("../../datasets/Task01_BrainTumour/test_images_for_model_prediction_submission/BRATS_485.nii.gz").get_fdata().astype(np.float32)

In [11]:
prediction = nib.load("../../submission_predictions/Task01_BrainTumor/BRATS_485.nii.gz").get_fdata().astype(np.uint8)

In [12]:
prediction.shape

(240, 240, 155)

In [13]:
np.unique(prediction)

array([0, 1, 2, 3], dtype=uint8)

#### Model prediction vs groundtruth number of labels

In [14]:
# Number of labels per class in model prediction
print("Background - class 0")
print(len(prediction[prediction == 0])) 
print("--------")
print("Edema - class 1")
print(len(prediction[prediction == 1]))
print("--------")
print("Non-Enhancing-Tumor - class 2")
print(len(prediction[prediction == 2]))
print("--------")
print("Enhancing-Tumor - class 3")
print(len(prediction[prediction == 3])) 

Background - class 0
8866196
--------
Edema - class 1
46081
--------
Non-Enhancing-Tumor - class 2
11244
--------
Enhancing-Tumor - class 3
4479


In [16]:
classes_dict = {
    'Background': 0,
    'Edema': 1,
    'Non-enhancing tumor': 2,
    'Enhancing tumor': 3 
}

# Create button values
select_class = ToggleButtons(
    options=['Background','Edema', 'Non-enhancing tumor', 'Enhancing tumor', 'All'],
    description='Select Class:',
    disabled=False,
    button_style='info', 
    
)
# Create layer slider
select_layer = IntSlider(min=0, max=mri.shape[2] - 1, description='Select Layer', continuous_update=False)

    
# Define a function for plotting images
def plot(seg_class, layer, channel):
    print(f"Plotting Layer: {layer} | Label: {seg_class} | Channel: {channel}")
    fig = plt.figure(figsize=(20, 10))
    
    fig.add_subplot(1, 2, 1)
    plt.title("MRI_BRATS_485", fontsize=20)
    plt.imshow(mri[:, :, layer, channel], cmap='gray');
    plt.axis('off')
  
    fig.add_subplot(1, 2, 2)
    if seg_class == "All":
        mask_model_prediction = prediction[:, :, layer]
        plt.title("Model prediction mask", fontsize=20)
        plt.imshow(mask_model_prediction)
        plt.axis('off');
    else:
        img_label = classes_dict[seg_class]
        mask_model_prediction = np.where(prediction[:, :, layer] == img_label, 255, 0)
        plt.title("Model prediction mask", fontsize=20)
        plt.imshow(mask_model_prediction, cmap='gray')
        plt.axis('off');

# Set channel to view:
#  Channel 0: "FLAIR" Fluid-attenuated inversion recovery
#  Channel 1: "T1w" T1-weighted
#  Channel 2: "t1gd" T1-weighted with gadolinium contrast enhancement
#  Channel 3: "T2w" T2-weighted    
    
# Use the interactive() tool to create the visualization
interactive(plot, seg_class=select_class, layer=select_layer, channel=(0, 3))

interactive(children=(ToggleButtons(button_style='info', description='Select Class:', options=('Background', '…

### Visualizing prediction on BRATS_486 file

In [17]:
mri = nib.load("../../datasets/Task01_BrainTumour/test_images_for_model_prediction_submission/BRATS_486.nii.gz").get_fdata().astype(np.float32)

In [18]:
prediction = nib.load("../../submission_predictions/Task01_BrainTumor/BRATS_486.nii.gz").get_fdata().astype(np.uint8)

In [19]:
prediction.shape

(240, 240, 155)

In [20]:
np.unique(prediction)

array([0, 1], dtype=uint8)

#### Model prediction vs groundtruth number of labels

In [21]:
# Number of labels per class in model prediction
print("Background - class 0")
print(len(prediction[prediction == 0])) 
print("--------")
print("Edema - class 1")
print(len(prediction[prediction == 1]))
print("--------")
print("Non-Enhancing-Tumor - class 2")
print(len(prediction[prediction == 2]))
print("--------")
print("Enhancing-Tumor - class 3")
print(len(prediction[prediction == 3])) 

Background - class 0
8916804
--------
Edema - class 1
11196
--------
Non-Enhancing-Tumor - class 2
0
--------
Enhancing-Tumor - class 3
0


In [23]:
classes_dict = {
    'Background': 0,
    'Edema': 1,
    'Non-enhancing tumor': 2,
    'Enhancing tumor': 3 
}

# Create button values
select_class = ToggleButtons(
    options=['Background','Edema', 'Non-enhancing tumor', 'Enhancing tumor', 'All'],
    description='Select Class:',
    disabled=False,
    button_style='info', 
    
)
# Create layer slider
select_layer = IntSlider(min=0, max=mri.shape[2] - 1, description='Select Layer', continuous_update=False)

    
# Define a function for plotting images
def plot(seg_class, layer, channel):
    print(f"Plotting Layer: {layer} | Label: {seg_class} | Channel: {channel}")
    fig = plt.figure(figsize=(20, 10))
    
    fig.add_subplot(1, 2, 1)
    plt.title("MRI_BRATS_486", fontsize=20)
    plt.imshow(mri[:, :, layer, channel], cmap='gray');
    plt.axis('off')
  
    fig.add_subplot(1, 2, 2)
    if seg_class == "All":
        mask_model_prediction = prediction[:, :, layer]
        plt.title("Model prediction mask", fontsize=20)
        plt.imshow(mask_model_prediction)
        plt.axis('off');
    else:
        img_label = classes_dict[seg_class]
        mask_model_prediction = np.where(prediction[:, :, layer] == img_label, 255, 0)
        plt.title("Model prediction mask", fontsize=20)
        plt.imshow(mask_model_prediction, cmap='gray')
        plt.axis('off');

# Set channel to view:
#  Channel 0: "FLAIR" Fluid-attenuated inversion recovery
#  Channel 1: "T1w" T1-weighted
#  Channel 2: "t1gd" T1-weighted with gadolinium contrast enhancement
#  Channel 3: "T2w" T2-weighted    
    
# Use the interactive() tool to create the visualization
interactive(plot, seg_class=select_class, layer=select_layer, channel=(0, 3))

interactive(children=(ToggleButtons(button_style='info', description='Select Class:', options=('Background', '…

### Visualizing prediction on BRATS_487 file

In [24]:
mri = nib.load("../../datasets/Task01_BrainTumour/test_images_for_model_prediction_submission/BRATS_487.nii.gz").get_fdata().astype(np.float32)

In [25]:
prediction = nib.load("../../submission_predictions/Task01_BrainTumor/BRATS_487.nii.gz").get_fdata().astype(np.uint8)

In [26]:
prediction.shape

(240, 240, 155)

In [27]:
np.unique(prediction)

array([0, 1, 2, 3], dtype=uint8)

#### Model prediction vs groundtruth number of labels

In [28]:
# Number of labels per class in model prediction
print("Background - class 0")
print(len(prediction[prediction == 0])) 
print("--------")
print("Edema - class 1")
print(len(prediction[prediction == 1]))
print("--------")
print("Non-Enhancing-Tumor - class 2")
print(len(prediction[prediction == 2]))
print("--------")
print("Enhancing-Tumor - class 3")
print(len(prediction[prediction == 3])) 

Background - class 0
8633107
--------
Edema - class 1
255335
--------
Non-Enhancing-Tumor - class 2
38502
--------
Enhancing-Tumor - class 3
1056


In [29]:
classes_dict = {
    'Background': 0,
    'Edema': 1,
    'Non-enhancing tumor': 2,
    'Enhancing tumor': 3 
}

# Create button values
select_class = ToggleButtons(
    options=['Background','Edema', 'Non-enhancing tumor', 'Enhancing tumor', 'All'],
    description='Select Class:',
    disabled=False,
    button_style='info', 
    
)
# Create layer slider
select_layer = IntSlider(min=0, max=mri.shape[2] - 1, description='Select Layer', continuous_update=False)

    
# Define a function for plotting images
def plot(seg_class, layer, channel):
    print(f"Plotting Layer: {layer} | Label: {seg_class} | Channel: {channel}")
    fig = plt.figure(figsize=(20, 10))
    
    fig.add_subplot(1, 2, 1)
    plt.title("MRI_BRATS_487", fontsize=20)
    plt.imshow(mri[:, :, layer, channel], cmap='gray');
    plt.axis('off')
  
    fig.add_subplot(1, 2, 2)
    if seg_class == "All":
        mask_model_prediction = prediction[:, :, layer]
        plt.title("Model prediction mask", fontsize=20)
        plt.imshow(mask_model_prediction)
        plt.axis('off');
    else:
        img_label = classes_dict[seg_class]
        mask_model_prediction = np.where(prediction[:, :, layer] == img_label, 255, 0)
        plt.title("Model prediction mask", fontsize=20)
        plt.imshow(mask_model_prediction, cmap='gray')
        plt.axis('off');

# Set channel to view:
#  Channel 0: "FLAIR" Fluid-attenuated inversion recovery
#  Channel 1: "T1w" T1-weighted
#  Channel 2: "t1gd" T1-weighted with gadolinium contrast enhancement
#  Channel 3: "T2w" T2-weighted    
    
# Use the interactive() tool to create the visualization
interactive(plot, seg_class=select_class, layer=select_layer, channel=(0, 3))

interactive(children=(ToggleButtons(button_style='info', description='Select Class:', options=('Background', '…