__Note__: The code used here was heavily inspired by the AI for Medicine Specialization Course 1 Week three programming assignments: [link](https://www.coursera.org/learn/ai-for-medical-diagnosis)

In [1]:
import numpy as np
import nibabel as nib
import matplotlib.pyplot as plt
import json
import os
from pprint import pprint
from collections import OrderedDict
from ipywidgets import interact, interactive, IntSlider, ToggleButtons
from sys import getsizeof
from tqdm import tqdm

### Checking lung_001 nifti MRI and mask files before and after splitting

### 1- Before

#### MRI file

In [2]:
mri_1 = nib.load("../../datasets/Task06_Lung/train/images/lung_001.nii.gz")

In [3]:
type(mri_1)

nibabel.nifti1.Nifti1Image

In [4]:
# Read Nifi Image object as numpy file
mri_1 = mri_1.get_fdata()

In [5]:
type(mri_1)

numpy.ndarray

In [6]:
mri_1.dtype

dtype('float64')

In [7]:
mri_1.shape

(512, 512, 304)

#### Mask file

In [8]:
mri_1_mask = nib.load("../../datasets/Task06_Lung/train/masks/lung_001.nii.gz")

In [9]:
mri_1_mask = mri_1_mask.get_fdata()

In [10]:
mri_1_mask.dtype

dtype('float64')

In [11]:
np.unique(mri_1_mask)

array([0., 1.])

In [12]:
mri_1_mask = mri_1_mask.astype(np.float32)

In [13]:
mri_1_mask.shape

(512, 512, 304)

### Visualizing original nifti MRI file and Mask file

In [14]:
# Create layer slider
select_layer = IntSlider(min=0, max=mri_1.shape[2] - 1, description='Select Layer', continuous_update=False)

    
# Define a function for plotting images
def plot(layer):
    print(f"Plotting Layer: {layer}")
    fig = plt.figure(figsize=(20, 10))
    
    fig.add_subplot(1, 2, 1)
    plt.imshow(mri_1[:, :, layer], cmap='gray');
    plt.title("ct", fontsize=20)
    plt.axis('off')
    
    fig.add_subplot(1, 2, 2)
    plt.title("Mask", fontsize=20)
    plt.imshow(mri_1_mask[:, :, layer], cmap='gray')
    plt.axis('off');

# Use the interactive() tool to create the visualization
interactive(plot, layer=select_layer)

interactive(children=(IntSlider(value=0, continuous_update=False, description='Select Layer', max=303), Output…

### 2- After

#### MRI file chunk 1

In [15]:
mri_1_after_chunk1 = nib.load("../../datasets/Task06_Lung_320x320x96/train/images/lung_001_0.nii.gz")

In [16]:
type(mri_1_after_chunk1)

nibabel.nifti1.Nifti1Image

In [17]:
# Read Nifi Image object as numpy file
mri_1_after_chunk1 = mri_1_after_chunk1.get_fdata().astype(np.float32)

In [18]:
type(mri_1_after_chunk1)

numpy.ndarray

In [19]:
mri_1_after_chunk1.dtype

dtype('float32')

In [20]:
mri_1_after_chunk1.shape

(320, 320, 96)

#### Mask file chunk 1

In [21]:
mri_1_mask_after_chunk1 = nib.load("../../datasets/Task06_Lung_320x320x96/train/masks/lung_001_0.nii.gz")

In [22]:
mri_1_mask_after_chunk1 = mri_1_mask_after_chunk1.get_fdata().astype(np.float32)

In [23]:
mri_1_mask_after_chunk1.dtype

dtype('float32')

In [24]:
np.unique(mri_1_mask_after_chunk1)

array([0.], dtype=float32)

In [25]:
mri_1_mask_after_chunk1 = mri_1_mask_after_chunk1.astype(np.float32)

In [26]:
mri_1_mask_after_chunk1.shape

(320, 320, 96)

In [27]:
# Create layer slider
select_layer = IntSlider(min=0, max=mri_1_after_chunk1.shape[2] - 1, description='Select Layer', continuous_update=False)

    
# Define a function for plotting images
def plot(layer):
    print(f"Plotting Layer: {layer}")
    fig = plt.figure(figsize=(20, 10))
    
    fig.add_subplot(1, 2, 1)
    plt.imshow(mri_1_after_chunk1[:, :, layer], cmap='gray');
    plt.title("ct", fontsize=20)
    plt.axis('off')
    
    fig.add_subplot(1, 2, 2)
    plt.title("Mask", fontsize=20)
    plt.imshow(mri_1_mask_after_chunk1[:, :, layer], cmap='gray')
    plt.axis('off');

# Use the interactive() tool to create the visualization
interactive(plot, layer=select_layer)

interactive(children=(IntSlider(value=0, continuous_update=False, description='Select Layer', max=95), Output(…

#### MRI file chunk 2

In [28]:
mri_1_after_chunk2 = nib.load("../../datasets/Task06_Lung_320x320x96/train/images/lung_001_1.nii.gz")

In [29]:
type(mri_1_after_chunk2)

nibabel.nifti1.Nifti1Image

In [30]:
# Read Nifi Image object as numpy file
mri_1_after_chunk2 = mri_1_after_chunk2.get_fdata().astype(np.float32)

In [31]:
type(mri_1_after_chunk2)

numpy.ndarray

In [32]:
mri_1_after_chunk2.dtype

dtype('float32')

In [33]:
mri_1_after_chunk2.shape

(320, 320, 96)

#### Mask file chunk 2

In [34]:
mri_1_mask_after_chunk2 = nib.load("../../datasets/Task06_Lung_320x320x96/train/masks/lung_001_1.nii.gz")

In [35]:
mri_1_mask_after_chunk2 = mri_1_mask_after_chunk2.get_fdata().astype(np.float32)

In [36]:
mri_1_mask_after_chunk2.dtype

dtype('float32')

In [37]:
np.unique(mri_1_mask_after_chunk2)

array([0.], dtype=float32)

In [38]:
mri_1_mask_after_chunk2 = mri_1_mask_after_chunk2.astype(np.float32)

In [39]:
mri_1_mask_after_chunk2.shape

(320, 320, 96)

### Visualizing nifti MRI file and Mask file

In [40]:
# Create layer slider
select_layer = IntSlider(min=0, max=mri_1_after_chunk2.shape[2] - 1, description='Select Layer', continuous_update=False)

    
# Define a function for plotting images
def plot(layer):
    print(f"Plotting Layer: {layer}")
    fig = plt.figure(figsize=(20, 10))
    
    fig.add_subplot(1, 2, 1)
    plt.imshow(mri_1_after_chunk2[:, :, layer], cmap='gray');
    plt.title("ct", fontsize=20)
    plt.axis('off')
    
    fig.add_subplot(1, 2, 2)
    plt.title("Mask", fontsize=20)
    plt.imshow(mri_1_mask_after_chunk2[:, :, layer], cmap='gray')
    plt.axis('off');

# Use the interactive() tool to create the visualization
interactive(plot, layer=select_layer)

interactive(children=(IntSlider(value=0, continuous_update=False, description='Select Layer', max=95), Output(…

#### MRI file chunk 3

In [41]:
mri_1_after_chunk3 = nib.load("../../datasets/Task06_Lung_320x320x96/train/images/lung_001_2.nii.gz")

In [42]:
type(mri_1_after_chunk3)

nibabel.nifti1.Nifti1Image

In [43]:
# Read Nifi Image object as numpy file
mri_1_after_chunk3 = mri_1_after_chunk3.get_fdata().astype(np.float32)

In [44]:
type(mri_1_after_chunk3)

numpy.ndarray

In [45]:
mri_1_after_chunk3.dtype

dtype('float32')

In [46]:
mri_1_after_chunk3.shape

(320, 320, 96)

#### Mask file chunk 3

In [47]:
mri_1_mask_after_chunk3 = nib.load("../../datasets/Task06_Lung_320x320x96/train/masks/lung_001_2.nii.gz")

In [48]:
mri_1_mask_after_chunk3 = mri_1_mask_after_chunk3.get_fdata().astype(np.float32)

In [49]:
mri_1_mask_after_chunk3.dtype

dtype('float32')

In [50]:
np.unique(mri_1_mask_after_chunk3)

array([0., 1.], dtype=float32)

In [51]:
mri_1_mask_after_chunk3 = mri_1_mask_after_chunk3.astype(np.float32)

In [52]:
mri_1_mask_after_chunk3.shape

(320, 320, 96)

### Visualizing nifti MRI file and Mask file

In [53]:
# Create layer slider
select_layer = IntSlider(min=0, max=mri_1_after_chunk3.shape[2] - 1, description='Select Layer', continuous_update=False)

    
# Define a function for plotting images
def plot(layer):
    print(f"Plotting Layer: {layer}")
    fig = plt.figure(figsize=(20, 10))
    
    fig.add_subplot(1, 2, 1)
    plt.imshow(mri_1_after_chunk3[:, :, layer], cmap='gray');
    plt.title("ct", fontsize=20)
    plt.axis('off')
    
    fig.add_subplot(1, 2, 2)
    plt.title("Mask", fontsize=20)
    plt.imshow(mri_1_mask_after_chunk3[:, :, layer], cmap='gray')
    plt.axis('off');

# Use the interactive() tool to create the visualization
interactive(plot, layer=select_layer)

interactive(children=(IntSlider(value=0, continuous_update=False, description='Select Layer', max=95), Output(…

#### MRI file chunk 4

In [54]:
mri_1_after_chunk4 = nib.load("../../datasets/Task06_Lung_320x320x96/train/images/lung_001_3.nii.gz")

In [55]:
type(mri_1_after_chunk4)

nibabel.nifti1.Nifti1Image

In [56]:
# Read Nifi Image object as numpy file
mri_1_after_chunk4 = mri_1_after_chunk4.get_fdata().astype(np.float32)

In [57]:
type(mri_1_after_chunk4)

numpy.ndarray

In [58]:
mri_1_after_chunk4.dtype

dtype('float32')

In [59]:
mri_1_after_chunk4.shape

(320, 320, 96)

#### Mask file chunk 4

In [60]:
mri_1_mask_after_chunk4 = nib.load("../../datasets/Task06_Lung_320x320x96/train/masks/lung_001_3.nii.gz")

In [61]:
mri_1_mask_after_chunk4 = mri_1_mask_after_chunk4.get_fdata().astype(np.float32)

In [62]:
mri_1_mask_after_chunk4.dtype

dtype('float32')

In [63]:
np.unique(mri_1_mask_after_chunk4)

array([0.], dtype=float32)

In [64]:
mri_1_mask_after_chunk4 = mri_1_mask_after_chunk4.astype(np.float32)

In [65]:
mri_1_mask_after_chunk4.shape

(320, 320, 96)

### Visualizing nifti MRI file and Mask file

In [66]:
# Create layer slider
select_layer = IntSlider(min=0, max=mri_1_after_chunk4.shape[2] - 1, description='Select Layer', continuous_update=False)

    
# Define a function for plotting images
def plot(layer):
    print(f"Plotting Layer: {layer}")
    fig = plt.figure(figsize=(20, 10))
    
    fig.add_subplot(1, 2, 1)
    plt.imshow(mri_1_after_chunk4[:, :, layer], cmap='gray');
    plt.title("ct", fontsize=20)
    plt.axis('off')
    
    fig.add_subplot(1, 2, 2)
    plt.title("Mask", fontsize=20)
    plt.imshow(mri_1_mask_after_chunk4[:, :, layer], cmap='gray')
    plt.axis('off');

# Use the interactive() tool to create the visualization
interactive(plot, layer=select_layer)

interactive(children=(IntSlider(value=0, continuous_update=False, description='Select Layer', max=95), Output(…